config/routes.rb
Rails.application.routes.draw do
  root to: 'homepage#index'

  get 'companies', to: 'homepage#companies'
  get 'readme', to: 'application#index'
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_and_belongs_to_many :languages, autosave: true

  validates :name, presence: true
  validates :logo_url, presence: true
  validates :website_url, presence: true
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_and_belongs_to_many :companies, autosave: true

  scope :trending, -> { order('(select COUNT(*) from companies_languages where language_id = languages.id) DESC').limit(20) }

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    @languages = Language.trending
  end

  def companies
    @companies = Company.includes(:languages).where(languages: { id: params[:ids].split(',') })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<h2>O Desafio</h2>

<p>Gostariamos que fosse implementado um protótipo semelhante ao <a href="https://startupstack.io" target="_blank">StartupStack</a>.</p>
<p>A aplicação deve usar a nossa API (<a href="https://github.com/LandingJobs/LandingJobs-api" target="_blank">https://github.com/LandingJobs/LandingJobs-api</a>) para obter os dados necessários (empresas e skills), mas deve guardar os dados na sua própria BD para não estar sempre a pedir os mesmos dados à API.</p>
<p>A applicação deve ler dados da API no máximo uma vez por hora. (Por uma questão de simplicidade, gera um API token para o teu utilizador aqui: <a href="https://landing.jobs/settings" target="_blank">https://landing.jobs/settings</a> e usa esse token para o acesso da API)</p>
<p>A nível de front-end, deve ter o mesmo tipo de funcionalidade do <a href="https://startupstack.io" target="_blank">https://startupstack.io</a>: Escolher uma ou mais skills para obter uma lista de empresas que procuram candidatos nessas tecnologias, com o nome e logo da empresa, e o link para o respectivo site.</p>
<p>Não precisam de fazer um design muito polido, mas queriamos ver algum trabalho de frontend. Funcional, nada demasiado complexo. Por exemplo, um layout semelhante ao do <a href="https://startupstack.io" target="_blank">https://startupstack.io</a></p>

app/views/homepage/_companies.html.erb
<%@companies.in_groups_of(6, false) do |companies| %>
  <div class="row">
    <%companies.each do |company| %>
      <div class="col-md-2">
        <%=link_to image_tag(company.logo_url, alt: company.name), company.website_url, target: '_blank', alt: company.name %>
        <%=company.name%>
      </div>
    <%end%>
  </div>
<%end%>

app/views/homepage/companies.js.erb
$('#companies').html('<%=j render 'companies'%>')

app/views/homepage/index.html.erb
<div class="container">
  <div class="languages">
    <%@languages.in_groups_of(4, false) do |languages|%>
      <div class="row">
        <%languages.each do |language| %>
          <div class="col-md-3">
            <%=link_to language.name, "#", class: 'language btn btn-default', id: dom_id(language), data: { id: language.id }%>
          </div>
        <%end%>
      </div>
    <%end%>
  </div>
  <hr>
  <div class="row">
    <div class="search-button col-md-12">
      <%=link_to "Search Companies", companies_path, remote: true, class: 'search btn btn-primary' %>
    </div>
  </div>
  <hr>
</div>
<div id="companies" class="container"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Landing Jobs Challenge</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <%= csrf_meta_tags %>
  </head>
  <body>
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-12085288-10', 'auto');
    ga('send', 'pageview');

    </script>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Landing Jobs Challenge", root_path, class: "navbar-brand" %>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="col-sm-3 col-md-2 sidebar">
        <ul class="nav nav-sidebar">
          <li class="active"><%= link_to "Home", root_path%></li>
          <li><%= link_to "About", readme_path%></li>
        </ul>
      </div>
      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <%=yield%>
      </div>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>